Update pythonanywhere_deploy.yml

diff --git a/.github/workflows/pythonanywhere_deploy.yml b/.github/workflows/pythonanywhere_deploy.yml
--- a/.github/workflows/pythonanywhere_deploy.yml
+++ b/.github/workflows/pythonanywhere_deploy.yml
@@ -21,6 +21,24 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
+    - name: Verify Secrets
+      env:
+        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
+        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
+      run: |
+        if [ -z "$PA_API_TOKEN" ]; then
+          echo "Error: PA_API_TOKEN is not set or empty."
+          exit 1
+        else
+          echo "PA_API_TOKEN is set."
+        fi
+
+        if [ -z "$PA_USERNAME" ]; then
+          echo "Error: PA_USERNAME is not set or empty."
+          exit 1
+        else
+          echo "PA_USERNAME is set."
+        fi
 
     - name: Deploy to PythonAnywhere
       env:
